### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jasonc624** [chrisguttandin/angular-prerender#134]
Is this built on top of scully?
Is this an alternative to scully?

Does this work with angular 17?

Can i render dynamic routes with this?  "my-route/:id"

**Comment by chrisguttandin** [comment]
Hi @jasonc624,

angular-prerender predates Scully. At some point I added the ability to use Scully plugins with angular-prerender to increase interoperability. But that's about it.

However there are a lot of similarities. Scully is for example also using the [guess-parser](https://www.npmjs.com/package/guess-parser) to detect routes. The major difference is that Scully (normally) uses Puppeteer to render routes and angular-prerender uses Node.js.

The current version of angular-prerender (v16) works with Angular v17. So far I've managed to keep angular-prerender up to date. However Angular's recent changes render many aspects of angular-prerender obsolete. At the same time, these changes are making it increasingly difficult to build something around the built-in prerendering capabilities. It's a bit ironic since Angular's prerender builder basically started with a copy of angular-prerender.

Yes, dynamic routes are supported. Please check the readme for more details.

https://github.com/chrisguttandin/angular-prerender/tree/master?tab=readme-ov-file#--parameter-values
